# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build_storybook:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing node modules
          command: |
            npm install
      # storybookをビルドする
      - run:
          name: build storybook
          command: yarn build-storybook
      # Artifactsにアップロードする
      - store_artifacts:
          path: ./storybook-static
          destination: ~/storybook/

orbs:
  node: circleci/node@4.1
workflows:
  version: 1
  default:
    jobs:
      - build_storybook:
        filters:
          branches:
            ignore: /develop.*/
# workflows:
#   sample:
#     jobs:
#       - node/test:
#           version: '15.1'
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
