# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

commands:
  build_storybook:
    steps:
      - run:
          name: Installing node modules
          command: npm install
      - run:
          name: build storybook
          command: yarn build-storybook
      - store_artifacts:
          path: ./storybook-static
  build_storybook_dev:
    steps:
      - run:
          name: Installing node modules
          command: npm install
      - run:
          name: build storybook
          command: yarn build-storybook
      - run:
          name: copy build
          command: cp ./storybook-static ./public/storybook/
      - store_artifacts:
          path: ./storybook-static

jobs:
  build_set:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - build_storybook
  build_set_dev:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout
      - build_storybook_dev

workflows:
  version: 1
  default:
    jobs:
      - build_set:
          filters:
            branches:
              ignore: /develop/
  develop:
    jobs:
      - build_set_dev:
          filters:
            branches:
              only: /develop/
# workflows:
#   sample:
#     jobs:
#       - node/test:
#           version: '15.1'
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
