# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6

commands:
  build_storybook:
    steps:
      - run:
          name: check node version
          command: node -v
      - run:
          name: Installing node modules
          command: npm install
      - run:
          name: build storybook
          command: yarn build-storybook
      - store_artifacts:
          path: ./storybook-static
  build_storybook_dev:
    steps:
      - run:
          name: check node version
          command: node -v
      - run:
          name: Installing node modules
          command: npm install
      - run:
          name: build storybook
          command: yarn build-storybook && mkdir ./public/storybook
      - run:
          name: copy build
          command: cp -r ./storybook-static/ ./public/storybook/
      - store_artifacts:
          path: ./storybook-static
  screenshot:
    steps:
      - run:
          name: screenshot
          command: yarn storycap
  regression:
    steps:
      # - name: Configure AWS credentials
      #     uses: aws-actions/configure-aws-credentials@v1
      #     with:
      #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #       aws-region: us-east-1
      - run:
          name: check node
          command: node -v
      - run:
          name: check root
          command: mkdir ~/.aws && cp .aws/credentials ~/.aws/credentials
      - run:
          name: check root
          command: ls -la ~/
      - run:
          name: regression
          command: yarn regression

jobs:
  aws-cli-cred-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
  build_set:
    executor:
      name: node/default
      tag: '16'
    docker:
      - image: circleci/node:14.16.1
    environment:
      TZ: "Asia/Tokyo"
    working_directory: ~/repo
    steps:
      - checkout
      - build_storybook
      - regression
  build_set_dev:
    docker:
      - image: circleci/node:14.16.1
    environment:
      TZ: "Asia/Tokyo"
    working_directory: ~/repo
    steps:
      - checkout
      - build_storybook_dev

workflows:
  version: 2
  default:
    jobs:
      - aws-cli-cred-setup:
          context: aws
          filters:
            branches:
              ignore: /(develop|main)/
      - build_set:
          filters:
            branches:
              ignore: /(develop|main)/
  develop:
    jobs:
      - build_set_dev:
          filters:
            branches:
              only: /develop/
# workflows:
#   sample:
#     jobs:
#       - node/test:
#           version: '15.1'
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node
